version: '3' #docker version
services:
  www:
    image: php:apache
    volumes:
      - "./:/var/www/html" # sync project dir with container web dir
    ports:
      - 80:80
      - 443:443  # for future ssl traffic
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=php_docker
      - MYSQL_USER=php_docker
      - MYSQL_PASSWORD=password # this should live in a env var
      - MYSQL_ROOT_PASSWORD=root_password_here # set a root password
      - MYSQL_ALLOW_EMPTY_PASSOWORD=1 # equivalent to True
    volumes:
      - "./db:/docker-entrypoint-initdb.d"  # sync persistent sql with container
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    depends_on:
      - db # Ensure the database service starts before phpMyAdmin

networks:
  default:
    driver: bridge 


    
  